apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeforge-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeforge
      version: blue
  template:
    metadata:
      labels:
        app: kubeforge
        version: blue
    spec:
      containers:
      - name: kubeforge-app
        image: 717562719168.dkr.ecr.ap-south-1.amazonaws.com/kubeforge-app:latest
        ports:
        - containerPort: 3000