apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeforge-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeforge
      version: green
  template:
    metadata:
      labels:
        app: kubeforge
        version: green
    spec:
      containers:
        - name: kubeforge-app
          image: 717562719168.dkr.ecr.ap-south-1.amazonaws.com/kubeforge-app:IMAGE_TAG
          ports:
            - containerPort: 3000

          # âœ… Health Checks (Production style)

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5