apiVersion: v1
kind: Service
metadata:
  name: kubeforge-service
spec:
  selector:
    app: kubeforge
    version: blue   # switch this to green later
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP